name: ds-academy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7,<=3.9
  - pip
  - notebook
  - numpy
  - ipywidgets
  - matplotlib
  - seaborn
  - scikit-learn
  - pandas
  - python-graphviz
  - requests
  - tensorflow
  - scikit-optimize
